services:
  novel-tracker:
    image: ghcr.io/julian447/novel-tracker:latest
    container_name: novel-tracker
    ports:
      - 8020:3000
    environment:
      JWT_SECRET: $JWT_SECRET
      NOVEL_UPDATE_MINUTES: 15
    volumes:
      - ./data:/app/data
    restart: unless-stopped
networks: {}
