services:
  novel-tracker:
    image: ghcr.io/julian447/novel-tracker:latest
    container_name: syosetu-tracker
    ports:
      - 3000:3000
    environment:
      JWT_SECRET: $JWT_SECRET
    volumes:
      - /data/syosetu-tracker:/app/data
    restart: unless-stopped
networks: {}
